services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: wp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - wordpress_network
    command: --default-authentication-plugin=mysql_native_password

  # WordPress
  wordpress:
    image: wordpress:latest
    platform: linux/arm64
    container_name: wp_wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', ${WORDPRESS_DEBUG});
        define('WP_DEBUG_LOG', ${WORDPRESS_DEBUG_LOG});
        define('WP_DEBUG_DISPLAY', ${WORDPRESS_DEBUG_DISPLAY});
        define('WP_ENVIRONMENT_TYPE', '${WP_ENVIRONMENT_TYPE}');
        define('SCRIPT_DEBUG', true);
        define('SAVEQUERIES', true);
        define('WP_MEMORY_LIMIT', '512M');
        ini_set('memory_limit', '512M');
        ini_set('max_execution_time', 300);
        ini_set('max_input_vars', 3000);
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content/plugins/plugin-template:/var/www/html/wp-content/plugins/plugin-template
      - ./wp-content/themes/hello-theme-child-master:/var/www/html/wp-content/themes/hello-theme-child-master
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./scripts:/scripts:ro
    ports:
      - "${WORDPRESS_PORT}:80"
    networks:
      - wordpress_network

  # phpMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: wp_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - wordpress_network

  # WP-CLI para automação
  wpcli:
    image: wordpress:cli-2.9-php8.2
    platform: linux/arm64
    container_name: wp_cli
    depends_on:
      - wordpress
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      HOME: /tmp
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content/plugins/plugin-template:/var/www/html/wp-content/plugins/plugin-template
      - ./wp-content/themes/hello-theme-child-master:/var/www/html/wp-content/themes/hello-theme-child-master
      - ./scripts:/scripts:ro
    networks:
      - wordpress_network
    working_dir: /var/www/html
    user: "33:33"  # www-data user
    command: tail -f /dev/null  # Manter container rodando

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mysql-data
  wordpress_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge

